### ISSUE TITLE
Cant install 

### ISSUE THREAD

**Issue by Lucas32578** [unmade/audiomatch#17]
'''
Collecting audiomatch
  Using cached audiomatch-0.2.1.tar.gz (29 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: audiomatch
  Building wheel for audiomatch (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for audiomatch (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      A setup.py file already exists. Using it.
      Traceback (most recent call last):
        File "/tmp/pip-install-i9bz7pf0/audiomatch_15dfee43325649da87f38ad6b0952d75/setup.py", line 2, in <module>
          from setuptools import setup
      ModuleNotFoundError: No module named 'setuptools'
      Traceback (most recent call last):
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-b9m9ibg4/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 67, in build_wheel
          return WheelBuilder.make_in(poetry, Path(wheel_directory))
        File "/tmp/pip-build-env-b9m9ibg4/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 79, in make_in
          wb.build(target_dir=directory)
        File "/tmp/pip-build-env-b9m9ibg4/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 113, in build
          self._build(zip_file)
        File "/tmp/pip-build-env-b9m9ibg4/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 167, in _build
          self._run_build_command(setup)
        File "/tmp/pip-build-env-b9m9ibg4/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 205, in _run_build_command
          subprocess.check_call(
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python', '/tmp/pip-install-i9bz7pf0/audiomatch_15dfee43325649da87f38ad6b0952d75/setup.py', 'build', '-b', '/tmp/pip-install-i9bz7pf0/audiomatch_15dfee43325649da87f38ad6b0952d75/build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for audiomatch
Failed to build audiomatch
ERROR: Could not build wheels for audiomatch, which is required to install pyproject.toml-based projects
'''

I have setuptools installed

OS: arch linux

**Comment by unmade** [comment]
Hey @Lucas32578 

Thanks for reporting the issue! The problem was in unpinned build-system version. I fixed it and released a new version. Please try to install it now:
```bash
pip install audiomatch==0.2.2
```

**Comment by Lucas32578** [comment]
works flawlessly now, thanks!
