### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by abcnorio** [unmade/audiomatch#20]
Hello,

OS: Debian bullseye

```
$ pip install audiomatch==0.2.2
Collecting audiomatch==0.2.2
  Using cached audiomatch-0.2.2.tar.gz (29 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: audiomatch
  Building wheel for audiomatch (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmp2m2lt39w_in_process.py build_wheel /tmp/tmp0nbghnz9
       cwd: /tmp/pip-install-z7tqi82t/audiomatch_e78a7e95d21c4f00a110bd350e82ecfb
  Complete output (26 lines):
  Traceback (most recent call last):
    File "/tmp/tmp2m2lt39w_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmp2m2lt39w_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmp2m2lt39w_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-5cy4fyqr/overlay/lib/python3.9/site-packages/poetry/masonry/api.py", line 59, in build_wheel
      WheelBuilder.make_in(
    File "/tmp/pip-build-env-5cy4fyqr/overlay/lib/python3.9/site-packages/poetry/masonry/builders/wheel.py", line 50, in make_in
      wb.build()
    File "/tmp/pip-build-env-5cy4fyqr/overlay/lib/python3.9/site-packages/poetry/masonry/builders/wheel.py", line 76, in build
      self._build(zip_file)
    File "/tmp/pip-build-env-5cy4fyqr/overlay/lib/python3.9/site-packages/poetry/masonry/builders/wheel.py", line 96, in _build
      self._env.run(
    File "/tmp/pip-build-env-5cy4fyqr/overlay/lib/python3.9/site-packages/poetry/utils/env.py", line 384, in run
      output = subprocess.check_output(
    File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.9/subprocess.py", line 505, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'python'

  ERROR: Failed building wheel for audiomatch
Failed to build audiomatch
ERROR: Could not build wheels for audiomatch which use PEP 517 and cannot be installed directly
```

and environment:

```
$ pip install setuptools
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (52.0.0)

$ pip -V
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)

```

What is missing?
Thanks and best!

**Comment by qarmin** [comment]
You need to install `python-is-python3` package

**Comment by abcnorio** [comment]
On Sun, 16 Oct 2022 00:30:55 -0700
Rafał Mikrut ***@***.***> wrote:

Thanks!
